# Etapa 1: build de la app
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

# --- NUEVO ---
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
# --------------

COPY . .
RUN npm run build

# Etapa 2: servir contenido estático
FROM node:20-slim
WORKDIR /app

RUN npm install -g serve
COPY --from=build /app/build ./build

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
